### PR TITLE
fixed deprecated usage of node-uuid in request dep

### PR DESCRIPTION
**Pull request by skarbovskiy**
2.45 version of request module currently produce 
```
    console.warn node_modules/node-uuid/uuid.js:48
      [SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()
```
more details here https://github.com/request/request/pull/2182

### CODE REVIEW

**Comment by FZambia** [comment]
Hello @skarbovskiy! Thanks a lot!

I hope with Centrifugo v2 developers will be able to integrate with Centrifugo a bit easier. Because there is no request signing. So sending API request is just sending simple JSON object. And tokens can  be generated using any JWT library.

**Comment by skarbovskiy** [comment]
waiting for v2 :)

**Comment by skarbovskiy** [comment]
@FZambia could u please upgrade published version

**Comment by FZambia** [comment]
@skarbovskiy sure, just did it.

**Pull request merged**
